<a href="https://colab.research.google.com/github/pooja17-png/Bag_of_Words_Demo/blob/main/Bag_of_Words.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv("test.csv")
df.head()

label                                               text
0   ham  Don't forget to bring the documents for tomorr...
1   ham            Let's catch up for coffee this weekend.
2   ham   Please find the attached report for your review.
3  spam  Get rich quick with this amazing investment op...
4   ham  Hi John, can we reschedule our meeting to next...

In [ ]:
df.label.value_counts()

label
spam    2013
ham     1987
Name: count, dtype: int64

In [ ]:
df['spam'] = df['label'].apply(lambda x: 1 if x =='spam' else 0)

In [ ]:
df.shape

(4000, 3)

In [ ]:
df.head()

label                                               text  spam
0   ham  Don't forget to bring the documents for tomorr...     0
1   ham            Let's catch up for coffee this weekend.     0
2   ham   Please find the attached report for your review.     0
3  spam  Get rich quick with this amazing investment op...     1
4   ham  Hi John, can we reschedule our meeting to next...     0

**Train test Split**

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df.text, df.spam, test_size=0.25)

In [ ]:
X_train.shape

(3000,)

In [ ]:
type(X_train)

pandas.core.series.Series

In [ ]:
X_train[:4]

983     URGENT: Your loan is approved. Call now to get...
1280           Happy birthday! Hope you have a great day!
2870     Please find the attached report for your review.
3552    Limited time offer! Buy one get one free on al...
Name: text, dtype: object

In [ ]:
type(y_train)

pandas.core.series.Series

In [ ]:
y_train[:4]

983     1
1280    0
2870    0
3552    1
Name: spam, dtype: int64

In [ ]:
type(X_train.values)

numpy.ndarray

**Creating bag of words representation using CountVectorizer**

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

v = CountVectorizer()

X_train_cv = v.fit_transform(X_train.values)
X_train_cv

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 30812 stored elements and shape (3000, 83)>

In [ ]:
X_train_cv.toarray()[:2][0]

array([0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1])

In [ ]:
X_train_cv.shape

(3000, 83)

In [ ]:
v.get_feature_names_out()[82]

'your'

In [ ]:
v.vocabulary_

{'urgent': 71,
 'your': 82,
 'loan': 45,
 'is': 40,
 'approved': 5,
 'call': 11,
 'now': 49,
 'to': 67,
 'get': 29,
 'funds': 28,
 'within': 79,
 '24': 1,
 'hours': 38,
 'happy': 32,
 'birthday': 8,
 'hope': 37,
 'you': 81,
 'have': 34,
 'great': 31,
 'day': 19,
 'please': 55,
 'find': 24,
 'the': 64,
 'attached': 6,
 'report': 57,
 'for': 25,
 'review': 59,
 'limited': 44,
 'time': 66,
 'offer': 50,
 'buy': 10,
 'one': 52,
 'free': 27,
 'on': 51,
 'all': 3,
 'items': 41,
 'shop': 61,
 'rich': 60,
 'quick': 56,
 'with': 78,
 'this': 65,
 'amazing': 4,
 'investment': 39,
 'opportunity': 53,
 'sign': 62,
 'up': 70,
 'today': 68,
 'dear': 20,
 'user': 72,
 'account': 2,
 'has': 33,
 'been': 7,
 'suspended': 63,
 'click': 16,
 'here': 35,
 'verify': 74,
 'details': 21,
 'hi': 36,
 'john': 42,
 'can': 12,
 'we': 76,
 'reschedule': 58,
 'our': 54,
 'meeting': 46,
 'next': 48,
 'monday': 47,
 'let': 43,
 'catch': 14,
 'coffee': 17,
 'weekend': 77,
 'congratulations': 18,
 've': 73,
 'won': 80

In [ ]:
X_train_np = X_train_cv.toarray()
X_train_np[0]

array([0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1])

In [ ]:
np.where(X_train_np[0]!=0)

(array([ 1,  5, 11, 28, 29, 38, 40, 45, 49, 67, 71, 79, 82]),)

In [ ]:
df.iloc[1579]  # It Works reliably based on position

label                                                  ham
text     Hi John, can we reschedule our meeting to next...
spam                                                     0
Name: 1579, dtype: object

In [ ]:
X_train_np[0][71]

np.int64(1)

*Training the Naive Bayes Model*

In [ ]:
from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB()
model.fit(X_train_cv, y_train)

MultinomialNB()

In [ ]:
X_test_cv = v.transform(X_test)

*Evaluating the Performance*

In [ ]:
from sklearn.metrics import classification_report

y_pred = model.predict(X_test_cv)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00       516
           1       1.00      1.00      1.00       484

    accuracy                           1.00      1000
   macro avg       1.00      1.00      1.00      1000
weighted avg       1.00      1.00      1.00      1000



In [ ]:
emails = [
    'Hey mohan, can we get together to watch footbal game tomorrow?',
    'Upto 20% discount on parking, exclusive offer just for you. Dont miss this reward!'
]

emails_count = v.transform(emails)
model.predict(emails_count)

array([0, 1])

*Training the model using sklearn pipeline and reduce number of lines of code*

In [ ]:
from sklearn.pipeline import Pipeline

clf = Pipeline([
    ('vectorizer', CountVectorizer()),
    ('nb', MultinomialNB())
])

In [ ]:
clf.fit(X_train, y_train)

Pipeline(steps=[('vectorizer', CountVectorizer()), ('nb', MultinomialNB())])

In [ ]:
y_pred = clf.predict(X_test)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00       516
           1       1.00      1.00      1.00       484

    accuracy                           1.00      1000
   macro avg       1.00      1.00      1.00      1000
weighted avg       1.00      1.00      1.00      1000

